### ISSUE TITLE
java.lang.StackOverflowError: null 	

### ISSUE THREAD

**Issue by mustafacoban96** [mustafacoban96/E-commerce#4]
at java.base/java.lang.Integer.toString(Integer.java:1192) ~[na:na] 	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453) ~[na:na] 	at com.shepherd.E_commerce.models.RefreshToken.toString(RefreshToken.java:26) ~[classes/:na] 	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453) ~[na:na] 	at com.shepherd.E_commerce.models.User.toString(User.java:46) ~[classes/:na] 	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453) ~[na:na] 	at com.shepherd.E_commerce.models.Cart.toString(Cart.java:17) ~[classes/:na]

**Comment by mustafacoban96** [comment]
I solved by using ToString.Exclude [projectlombok/lombok/issues/2255](here),[https://github.com/projectlombok/lombok/issues/1007](here),[https://github.com/projectlombok/lombok/issues/276](offical lombok)
